# -*- coding: utf-8 -*-
"""ML_modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2tETIhQeBy6FdzUgNwTYGAZ8fgebrqL
"""



from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import xgboost as xgb
import shap

print("\n" + "="*50)
print("🚀 ADVANCED ANALYSIS 1: TRADER CLUSTERING (SMART MONEY)")
print("="*50)

# 1. Aggregate data per individual trader (account)
trader_profiles = merged_df.groupby('account').agg(
    total_trades=('closed_pnl', 'count'),
    win_rate=('is_win', 'mean'),
    # Removed 'avg_leverage' as 'leverage' column does not exist
    total_pnl=('closed_pnl', 'sum'),
    avg_size=('size_usd', 'mean') # Changed 'size' to 'size_usd'
).reset_index()

# Filter out accounts with too few trades to avoid statistical noise
trader_profiles = trader_profiles[trader_profiles['total_trades'] >= 5].copy()

# 2. Prepare features for clustering
# Removed 'avg_leverage' from features for clustering
features_for_clustering = ['win_rate', 'total_pnl', 'avg_size']
scaler = StandardScaler()
scaled_features = scaler.fit_transform(trader_profiles[features_for_clustering])

# 3. Apply K-Means Clustering (Finding 3 distinct types of traders)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
trader_profiles['Cluster'] = kmeans.fit_predict(scaled_features)

# Rename clusters logically based on their characteristics
cluster_means = trader_profiles.groupby('Cluster')['total_pnl'].mean()
sorted_clusters = cluster_means.sort_values().index
cluster_names = {
    sorted_clusters[0]: "The Degens (High Loss)",
    sorted_clusters[1]: "The Retail Crowd (Break-even)",
    sorted_clusters[2]: "Smart Money (Highly Profitable)"
}
trader_profiles['Trader_Type'] = trader_profiles['Cluster'].map(cluster_names)

print("\nTrader Cohort Profiles:")
print(trader_profiles.groupby('Trader_Type')[features_for_clustering + ['total_trades']].mean().round(2).to_string())

# 4. Visualize the Clusters
plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=trader_profiles,
    x='avg_size', # Changed x-axis from 'avg_leverage' to 'avg_size'
    y='win_rate',
    hue='Trader_Type',
    size='total_pnl',
    sizes=(20, 400),
    alpha=0.7,
    palette=['#d73027', '#e0e0e0', '#1a9850']
)
plt.title('Trader Profiling: Average Position Size vs Win Rate (Bubble Size = Total PnL)', fontweight='bold') # Updated title
plt.xlabel('Average Position Size (USD)') # Updated x-label
plt.ylabel('Win Rate')
plt.axhline(0.5, color='black', linestyle='--', alpha=0.5, label='50% Win Rate')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()



print("\n" + "="*50)
print("🔮 ADVANCED ANALYSIS 2: XGBOOST TRADE SUCCESS PREDICTOR")
print("="*50)

# 1. Prepare ML dataset
ml_df = merged_df.copy()

# Convert categorical Sentiment to numbers (0=Extreme Fear, 4=Extreme Greed)
le = LabelEncoder()
ml_df['sentiment_encoded'] = le.fit_transform(ml_df['classification']) # Changed 'Classification' to 'classification'

# Select Features (X) and Target (y)
# Removed 'leverage' and changed 'size' to 'size_usd'
features = ['size_usd', 'sentiment_encoded', 'is_long']
X = ml_df[features]
y = ml_df['is_win'].astype(int)

# 2. Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 3. Train XGBoost Classifier
xgb_model = xgb.XGBClassifier(
    n_estimators=100,
    max_depth=4,
    learning_rate=0.05,
    random_state=42,
    eval_metric='logloss'
)
xgb_model.fit(X_train, y_train)

# 4. Evaluate Model
y_pred = xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy in predicting if a trade will win/lose: {accuracy*100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Loss (0)', 'Win (1)']))

# 5. SHAP Explainability (Why do trades win or lose?)
print("\nGenerating SHAP Analysis to show what drives a winning trade...")
explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_test)

plt.figure(figsize=(10, 6))
# We replace the encoded sentiment integers with their actual names just for the plot labels
X_test_display = X_test.copy()
X_test_display['sentiment_encoded'] = le.inverse_transform(X_test['sentiment_encoded'])

# Updated feature_names to match the new features
shap.summary_plot(shap_values, X_test_display, feature_names=['Position Size (USD)', 'Market Sentiment', 'Is Long?'])