# -*- coding: utf-8 -*-
"""Trade_behaviour_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112NtA32rul7vETWH8K8un7umDknb0mVU
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from scipy import stats
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

fear_greed_df  = pd.read_csv("fear_greed_index.csv")
trader_df =pd.read_csv("historical_data.csv")

def get_df_info(df):

    print("\n\033[1mShape of DataFrame:\033[0m ", df.shape)
    print("\n\033[1mColumns in DataFrame:\033[0m ", df.columns.to_list())
    print("\n\033[1mInformation about DataFrame:\033[0m")
    df.info()
    print("\n\033[1mUnique values per column:\033[0m")
    print(df.nunique())
    print("\n\033[1mNull values:\033[0m\n", df.isnull().sum())
    print("\n\033[1mDuplicate rows:\033[0m ", df.duplicated().sum())
    print("\n\033[1mDescriptive statistics:\033[0m\n", df.describe().transpose())

get_df_info(fear_greed_df)

get_df_info(trader_df)

# Fear greed Data
fear_greed_df.columns = fear_greed_df.columns.str.strip().str.lower()
fear_greed_df["date"] = pd.to_datetime(fear_greed_df["date"])
fear_greed_df["classification"] = fear_greed_df["classification"].str.strip()
fear_greed_df = fear_greed_df.dropna(subset=["date","classification"])

fear_greed_df.head()

#Trader Data
trader_df.columns = (trader_df.columns.str.strip()
                        .str.lower()
                        .str.replace(" ","_")
                        .str.replace(r"[^a-z0-9_]","",regex=True))

trader_df.head()

# Cleaning and Merging Data

# 1. Standardize the Dates

trader_df['date'] = pd.to_datetime(trader_df['timestamp'], unit='ms', errors='coerce').dt.normalize()
fear_greed_df['date'] = pd.to_datetime(fear_greed_df['date'], errors='coerce').dt.normalize()

trader_df['closed_pnl'] = pd.to_numeric(trader_df['closed_pnl'], errors='coerce').fillna(0)

trader_df['is_long'] = trader_df['side'].astype(str).str.upper().isin(['BUY', 'LONG', 'B'])
trader_df['is_win'] = trader_df['closed_pnl'] > 0
trader_df['abs_pnl'] = trader_df['closed_pnl'].abs()

merged_df = pd.merge(trader_df, fear_greed_df, on='date', how='inner')

sentiment_order = ['Extreme Fear', 'Fear', 'Neutral', 'Greed', 'Extreme Greed']
merged_df['classification'] = pd.Categorical(
    merged_df['classification'],
    categories=sentiment_order,
    ordered=True
)

merged_df.head()

print(f"Total trades after merge: {len(merged_df):,}")
print(f"Total unique days matched: {merged_df['date'].nunique()}")
print("\nSentiment Breakdown:")
print(merged_df['classification'].value_counts().sort_index().to_string())

"""- During this 6-day window, the market was predominantly bleeding or scared.
- Nearly 3 out of every 4 trades happened while the Fear & Greed index was in "Fear".
"""

print("--- Analyzing Sentiment Distribution ---")

sentiment_order = ['Extreme Fear', 'Fear', 'Neutral', 'Greed', 'Extreme Greed']
sentiment_colors = ['#d73027', '#f46d43', '#e0e0e0', '#a6d96a', '#1a9850']


vc = fear_greed_df['classification'].value_counts().reindex(sentiment_order).dropna()

# 3. Create the Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(
    vc,
    labels=vc.index,
    colors=sentiment_colors,
    autopct="%1.1f%%",
    startangle=90,
    wedgeprops={"edgecolor": "white", "linewidth": 2}
)

plt.title("All-Time Bitcoin Market Sentiment\n(Fear & Greed Index)", fontsize=14, fontweight='bold', pad=20)
plt.show()

import matplotlib.dates as mdates

print("--- Plotting Sentiment Timeline & Trade Distribution ---")

# 1. Setup the figure with 2 side-by-side plots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))
sentiment_order = ['Extreme Fear', 'Fear', 'Neutral', 'Greed', 'Extreme Greed']
sentiment_colors = ['#d73027', '#f46d43', '#e0e0e0', '#a6d96a', '#1a9850']

# B: Sentiment Timeline (2024)

fg24 = fear_greed_df[(fear_greed_df['date'] >= '2024-01-01') & (fear_greed_df['date'] <= '2024-12-31')]
ax1.plot(fg24['date'], fg24['value'], color='#22C55E', linewidth=1.5)
ax1.fill_between(fg24['date'], fg24['value'], color='#22C55E', alpha=0.2)

ax1.axhline(25, color='#d73027', linestyle='--', alpha=0.7, label='Extreme Fear (<25)')
ax1.axhline(45, color='#f46d43', linestyle='--', alpha=0.7, label='Fear (<45)')
ax1.axhline(55, color='#e0e0e0', linestyle='--', alpha=0.7, label='Neutral (45-55)')
ax1.axhline(75, color='#a6d96a', linestyle='--', alpha=0.7, label='Greed (>75)')

ax1.set_title("Fear/Greed Index — 2024", fontsize=12, fontweight='bold')
ax1.set_ylim(0, 100)
ax1.legend(loc="lower right", fontsize=8) # Moved lower right so it doesn't block data
ax1.xaxis.set_major_formatter(mdates.DateFormatter("%b")) # Shows 'Jan', 'Feb', etc.

# C: Trade Count per Sentiment Bar Chart

tc = merged_df['classification'].value_counts().reindex(sentiment_order).dropna()

bars = ax2.bar(tc.index, tc.values, color=sentiment_colors, edgecolor='black', linewidth=1)

# Add the text numbers perfectly on top of each bar
for bar in bars:
    ax2.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + (tc.max() * 0.02), # Add a tiny vertical offset so text floats
        f"{int(bar.get_height()):,}",         # Format with commas (e.g., 1,500)
        ha="center", fontsize=10, fontweight='bold'
    )

ax2.set_title("Total Trades per Sentiment Regime", fontsize=12, fontweight='bold')
ax2.set_ylabel("Trade Count")
ax2.tick_params(axis="x", rotation=15) # Tilt the labels slightly to prevent overlapping


plt.tight_layout()
plt.show()

print("--- Trader PnL Overview ---")

# 1. Calculate Core Statistics
total_pnl = merged_df["closed_pnl"].sum()
mean_pnl  = merged_df["closed_pnl"].mean()
win_rate  = merged_df["is_win"].mean() * 100
n_trades  = len(merged_df)

print(f"Total closed PnL : ${total_pnl:,.2f}")
print(f"Mean PnL/trade   : ${mean_pnl:,.4f}")
print(f"Win rate         : {win_rate:.2f}%")
print(f"Total trades     : {n_trades:,}")
print(f"Unique accounts  : {merged_df['account'].nunique():,}")
if "symbol" in merged_df.columns:
    print(f"Symbols traded   : {merged_df['symbol'].nunique():,}")

# 2. Setup the figure for 3 side-by-side charts
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

#  Plot A: PnL Distribution (Histogram)
pnl_clipped = merged_df["closed_pnl"].clip(-500, 500) # Prevents massive outliers from ruining the chart

axes[0].hist(pnl_clipped[merged_df["closed_pnl"] < 0], bins=60, color='#d73027', alpha=0.8, label="Losses")
axes[0].hist(pnl_clipped[merged_df["closed_pnl"] > 0], bins=60, color='#1a9850', alpha=0.8, label="Wins")

axes[0].axvline(0, color="black", lw=1.2, ls="--")
axes[0].axvline(mean_pnl, color="blue", lw=1.5, ls="-.", label=f"Mean = ${mean_pnl:.2f}")

axes[0].set_title("PnL Distribution (Clipped ±$500)", fontweight='bold')
axes[0].set_xlabel("Closed PnL ($)")
axes[0].set_ylabel("Number of Trades")
axes[0].legend()

#  Plot B: Cumulative PnL Over Time (Line Chart)
# Group by Date and calculate the running total
daily_pnl = merged_df.groupby("date")["closed_pnl"].sum().sort_index()
cum_pnl   = daily_pnl.cumsum()

axes[1].plot(cum_pnl.index, cum_pnl.values, color="black", lw=1.5)

# Fill green if the portfolio is in profit, red if in drawdown
axes[1].fill_between(cum_pnl.index, cum_pnl.values, where=(cum_pnl.values >= 0), color="#1a9850", alpha=0.3)
axes[1].fill_between(cum_pnl.index, cum_pnl.values, where=(cum_pnl.values < 0), color="#d73027", alpha=0.3)

axes[1].axhline(0, color="black", lw=0.8, ls="--")
axes[1].set_title("Cumulative PnL Over Time", fontweight='bold')
axes[1].set_ylabel("Cumulative PnL ($)")

# Format the Y-axis to show dollars and X-axis to show Months
axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, pos: f"${x:,.0f}"))
axes[1].xaxis.set_major_formatter(mdates.DateFormatter("%b"))



#  Plot C: Win / Loss Ratio (Bar Chart)
wins = int(merged_df["is_win"].sum())
losses = n_trades - wins

bars = axes[2].bar(['Wins', 'Losses'], [wins, losses], color=['#1a9850', '#d73027'], edgecolor='black')

for i, val in enumerate([wins, losses]):
    axes[2].text(
        i, val + (n_trades * 0.02),
        f"{val:,}\n({(val/n_trades)*100:.1f}%)",
        ha="center", fontweight='bold', fontsize=10
    )

axes[2].set_title("Win / Loss Split", fontweight='bold')
axes[2].set_ylabel("Trade Count")
axes[2].set_ylim(0, max(wins, losses) * 1.2)

plt.tight_layout()
plt.show()

print("--- PnL by Sentiment Regime ---")

# 1. Calculate Aggregated Statistics
sent_pnl = merged_df.groupby("classification", observed=True)["closed_pnl"].agg(
    ["mean", "median", "sum", "std", "count"]
).rename(columns={
    "mean": "Avg PnL", "median": "Median PnL",
    "sum": "Total PnL", "std": "Std Dev", "count": "Trades"
})

print("\nStatistical Summary by Sentiment:")
print(sent_pnl.round(2).to_string())

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
sentiment_order = ['Extreme Fear', 'Fear', 'Neutral', 'Greed', 'Extreme Greed']
sentiment_colors = ['#d73027', '#f46d43', '#e0e0e0', '#a6d96a', '#1a9850']

# Plot A: Average PnL per Trade (Bar Chart)
bars1 = axes[0].bar(sent_pnl.index, sent_pnl["Avg PnL"], color=sentiment_colors, edgecolor="black")
axes[0].axhline(0, color="black", lw=1, ls="--")

for b in bars1:
    v = b.get_height()
    offset = 0.5 if v >= 0 else -2.5
    axes[0].text(b.get_x() + b.get_width()/2, v + offset, f"${v:.2f}", ha="center", fontsize=9, fontweight='bold')

axes[0].set_title("Average PnL per Trade", fontweight='bold')
axes[0].set_ylabel("Avg Closed PnL ($)")
axes[0].tick_params(axis="x", rotation=15)

#  Plot B: PnL Distribution Boxplot
merged_df['closedPnL_clipped'] = merged_df['closed_pnl'].clip(-200, 200)

sns.boxplot(
    data=merged_df,
    x='classification',
    y='closedPnL_clipped',
    ax=axes[1],
    palette=sentiment_colors,
    order=sentiment_order,
    showfliers=True,
    flierprops={"marker":"o", "ms":3, "alpha":0.3} # Format outlier dots
)

axes[1].axhline(0, color="black", lw=1, ls="--")
axes[1].set_title("PnL Distribution (Clipped ±$200)", fontweight='bold')
axes[1].set_ylabel("Closed PnL ($)")
axes[1].set_xlabel("")
axes[1].tick_params(axis="x", rotation=15)



# Plot C: Total PnL Captured (Bar Chart)
bars3 = axes[2].bar(sent_pnl.index, sent_pnl["Total PnL"], color=sentiment_colors, edgecolor="black")
axes[2].axhline(0, color="black", lw=1, ls="--")

axes[2].set_title("Total PnL Captured", fontweight='bold')
axes[2].set_ylabel("Total Closed PnL ($)")
axes[2].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, pos: f"${x:,.0f}"))
axes[2].tick_params(axis="x", rotation=15)

plt.tight_layout()
plt.show()

# Clean up the temporary column so it doesn't mess up future analysis
merged_df.drop(columns=['closedPnL_clipped'], inplace=True)

# use our standard colors and order
sentiment_order = ['Extreme Fear', 'Fear', 'Neutral', 'Greed', 'Extreme Greed']
sentiment_colors = ['#d73027', '#f46d43', '#e0e0e0', '#a6d96a', '#1a9850']

print("\n" + "="*50)
print("--- Win Rate & Trade Quality by Sentiment ---")
print("="*50)

# 1. Calculate Aggregations
wr = merged_df.groupby("classification", observed=True).agg(
    Total=('is_win', 'count'),
    Wins=('is_win', 'sum'),
    Win_Rate=('is_win', 'mean')
)

wr["Win Rate %"] = wr["Win_Rate"] * 100
wr["Avg Win"] = merged_df[merged_df["is_win"]].groupby("classification", observed=True)["closed_pnl"].mean()
wr["Avg Loss"] = merged_df[~merged_df["is_win"]].groupby("classification", observed=True)["closed_pnl"].mean()
wr["Profit Factor"] = wr["Avg Win"] / wr["Avg Loss"].abs()

print("\nTrade Quality Summary:")
print(wr[["Win Rate %", "Wins", "Total", "Avg Win", "Avg Loss", "Profit Factor"]].round(2).to_string())

# 2. Plotting Section 6
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# ── Plot A: Win Rate Bar Chart ──
bars_wr = axes[0].bar(wr.index, wr["Win Rate %"], color=sentiment_colors, edgecolor="black")
axes[0].axhline(50, color="black", lw=1.2, ls="--", alpha=0.7, label="50% Baseline")

for b in bars_wr:
    axes[0].text(b.get_x() + b.get_width()/2, b.get_height() + 1,
                 f"{b.get_height():.1f}%", ha="center", fontsize=9, fontweight='bold')

axes[0].set_title("Win Rate by Sentiment Regime", fontweight='bold')
axes[0].set_ylabel("Win Rate (%)")
axes[0].set_ylim(0, max(wr["Win Rate %"]) * 1.2)
axes[0].tick_params(axis="x", rotation=15)
axes[0].legend()

# ── Plot B: Avg Win vs Avg Loss (Grouped Bar Chart) ──
x = np.arange(len(wr))
w = 0.35

axes[1].bar(x - w/2, wr["Avg Win"].values, w, color="#1a9850", edgecolor="black", label="Avg Win")
axes[1].bar(x + w/2, wr["Avg Loss"].abs().values, w, color="#d73027", edgecolor="black", label="Avg Loss Magnitude")

axes[1].set_xticks(x)
axes[1].set_xticklabels(wr.index, rotation=15)
axes[1].set_title("Avg Win vs Avg Loss Magnitude", fontweight='bold')
axes[1].set_ylabel("Dollars ($)")
axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda val, pos: f"${val:,.0f}"))
axes[1].legend()



# ── Plot C: Profit Factor ──
pf_clipped = wr["Profit Factor"].fillna(0).clip(upper=5) # Clip extreme outliers
bars_pf = axes[2].bar(wr.index, pf_clipped.values, color=sentiment_colors, edgecolor="black")
axes[2].axhline(1.0, color="black", lw=1.2, ls="--", label="Break-even (1.0x)")

for b in bars_pf:
    axes[2].text(b.get_x() + b.get_width()/2, b.get_height() + 0.1,
                 f"{b.get_height():.2f}x", ha="center", fontsize=9, fontweight='bold')

axes[2].set_title("Profit Factor by Sentiment", fontweight='bold')
axes[2].set_ylabel("Profit Factor (Win / Loss ratio)")
axes[2].tick_params(axis="x", rotation=15)
axes[2].legend()

plt.tight_layout()
plt.show()

"""**The "Smart Money" Paradox (Win Rate vs. PnL)**

- The Retail Crowd wins 69% of the time, generating $389k.

- Smart Money wins only 37% of the time, but generates $768k (Double the profit!).

 This just proved the Disposition Effect. Retail traders take profits too early just to get a "Win" (giving them a 69% win rate), but when they lose, they lose massive amounts of money.

Smart Money, on the other hand, is completely fine losing 63% of their trades. Because they practice strict risk management—they cut their losses instantly at -$100, but when they win,they  ride it for +$5,000.

**Sizing is the True Edge**


- Retail is trading $2,668 per trade.
- Smart Money is throwing down $20,208 per trade.

- The Degens are trading $5,298 per trade but have the worst win rate (30%) and lowest PnL.

 Degens are over-leveraging mid-sized accounts and getting liquidated. Smart Money isn't using 100x leverage; they are simply using larger base capital and trading highly strategic setups.

**This Machine Learning model can look at a trader's Leverage, Size, Long/Short direction, and the Fear/Greed Sentiment, and correctly predict if that trade will lose money 66 percent of time.**

**The "Trend is your Friend" Proof**

- Look at the bright Red dots (which means Is Long? = True). They are entirely clustered on the Left side. This means taking a Long position strongly pushed the model to predict a Loss.

- Look at the Blue dots (which means Is Long? = False, so they went Short). They are clustered on the Right side. Going Short strongly pushed the model to predict a Win.

This captured a "bleeding" market. Since we already know 72% of this 6-day window was in "Fear," the model figured out that anyone trying to "buy the dip" (going Long) was getting crushed. The traders who traded with the fear (going Short) were the ones making money.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mticker

print("\n" + "="*60)
print("🧠 BEHAVIORAL FINANCE: PROVING PSYCHOLOGY WITH DATA")
print("="*60)

# ==========================================
# 1. WHALE VS RETAIL SEGMENTATION
# ==========================================
# We define "Whales" as the top 5% of trade sizes, "Dolphins" as the next 15%, and "Retail" as the bottom 80%
size_threshold_95 = merged_df['size_usd'].quantile(0.95)
size_threshold_80 = merged_df['size_usd'].quantile(0.80)

def segment_traders(size):
    if size >= size_threshold_95:
        return 'Whales (Top 5%)'
    elif size >= size_threshold_80:
        return 'Dolphins (Top 20%)'
    else:
        return 'Retail (Bottom 80%)'

merged_df['Trader_Cohort'] = merged_df['size_usd'].apply(segment_traders)

print(f"\n🐋 Segmentation Thresholds:")
print(f"Retail trades are under: ${size_threshold_80:,.2f} in size")
print(f"Whale trades are over:   ${size_threshold_95:,.2f} in size")

# ==========================================
# 2. THE FOMO METRIC (Momentum Chasing)
# ==========================================
# Do Retail traders go Long during Extreme Greed while Whales go Short?
fomo_df = merged_df[merged_df['classification'] == 'Extreme Greed']
fomo_stats = fomo_df.groupby('Trader_Cohort', observed=True).agg(
    Total_Greed_Trades=('is_win', 'count'),
    Percent_Going_Long=('is_long', lambda x: (x.mean() * 100).round(1))
    # Removed 'Average_Leverage' as 'leverage' column does not exist
).reindex(['Retail (Bottom 80%)', 'Dolphins (Top 20%)', 'Whales (Top 5%)'])

print("\n📈 FOMO BEHAVIOR DURING 'EXTREME GREED':")
print(fomo_stats.to_string())

# ==========================================
# 3. DISPOSITION EFFECT (Holding Losers)
# ==========================================
# Are traders cutting winners short and holding losers to zero?
disp_stats = merged_df.groupby('Trader_Cohort', observed=True).apply(
    lambda x: pd.Series({
        'Avg_Win_Size ($)': x[x['is_win']]['closed_pnl'].mean(),
        'Avg_Loss_Size ($)': x[~x['is_win']]['closed_pnl'].abs().mean()
    })
)
disp_stats['Loss_to_Win_Ratio'] = disp_stats['Avg_Loss_Size ($)'] / disp_stats['Avg_Win_Size ($)']

print("\n📉 DISPOSITION EFFECT (Are Losses larger than Wins?):")
print(disp_stats.round(2).to_string())

# ==========================================
# 4. VISUALIZING PSYCHOLOGY
# ==========================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
cohort_colors = {'Retail (Bottom 80%)': '#f46d43', 'Dolphins (Top 20%)': '#a6d96a', 'Whales (Top 5%)': '#1a9850'}

# ── A. Risk Seeking (Average Trade Size by Cohort) ──
sns.barplot(data=merged_df, x='Trader_Cohort', y='size_usd', ax=axes[0], palette=cohort_colors, edgecolor='black', order=['Retail (Bottom 80%)', 'Dolphins (Top 20%)', 'Whales (Top 5%)'], estimator=np.mean)
axes[0].set_title('Risk-Seeking: Average Trade Size by Cohort', fontweight='bold')
axes[0].set_ylabel('Average Trade Size (USD)')
axes[0].tick_params(axis="x", rotation=15)
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda val, pos: f"${val:,.0f}"))

# ── B. The FOMO Metric (Long bias in Extreme Greed) ──
bars = axes[1].bar(fomo_stats.index, fomo_stats['Percent_Going_Long'], color=[cohort_colors[x] for x in fomo_stats.index], edgecolor='black')
axes[1].axhline(50, color="black", lw=1.2, ls="--", label="50% (Neutral Bias)")
for b in bars:
    axes[1].text(b.get_x() + b.get_width()/2, b.get_height() + 2, f"{b.get_height()}%", ha="center", fontweight='bold')
axes[1].set_title('FOMO: % Going LONG during "Extreme Greed"', fontweight='bold')
axes[1].set_ylabel('% of Trades that are Buy/Long')
axes[1].set_ylim(0, 100)
axes[1].tick_params(axis="x", rotation=15)


# ── C. The Disposition Effect (Win/Loss Size) ──
x = np.arange(len(disp_stats))
w = 0.35
axes[2].bar(x - w/2, disp_stats['Avg_Win_Size ($)'], w, color='#1a9850', edgecolor='black', label='Avg Win Profit')
axes[2].bar(x + w/2, disp_stats['Avg_Loss_Size ($)'], w, color='#d73027', edgecolor='black', label='Avg Loss Damage')
axes[2].set_xticks(x)
axes[2].set_xticklabels(disp_stats.index, rotation=15)
axes[2].set_title('Disposition Effect: Win Size vs Loss Size', fontweight='bold')
axes[2].set_ylabel('Dollars ($)')
axes[2].yaxis.set_major_formatter(mticker.FuncFormatter(lambda val, pos: f"${val:,.0f}"))
axes[2].legend()

plt.tight_layout()
plt.show()